apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: opensearch
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  opensearch:
    host: opensearch-logging-data.kubesphere-logging-system.svc
    port: 9200
    generateID: true
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"