apiVersion: fluentbit.fluent.io
kind: ClusterOutput
metadata:
  name: auditd-to-opensearch
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: auditd
  es:
    host: opensearch-logging-data.kubesphere-logging-system.svc
    port: 9200
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"